### ISSUE TITLE
Does it support BN curve?

### ISSUE THREAD

**Issue by VegeBun-csj** [arkworks-rs/groth16#49]
it support bn128 or bn256 curve?

**Comment by mmagician** [comment]
Yes, it is generic over pairing-friendly curves.
You can see an example [here](https://github.com/arkworks-rs/groth16/blob/master/tests/mimc.rs#L168). In the case of `bn254` (I assume you mean that one, see [here](https://hackmd.io/@jpw/bn254)), you'd replace the bls part with `Bn254` from the [arkworks-rs/curves](https://github.com/arkworks-rs/curves/blob/5a41d7f27a703a7ea9c48512a4148443ec6c747e/bn254/src/curves/mod.rs#L44).
