### ISSUE TITLE
Invalid circuit when using a snarkjs zkey

### ISSUE THREAD

**Issue by vaqxai** [arkworks-rs/groth16#65]
## Summary of Bug

When trying to use a zkey read from a .zkey file (imported `using ark_circom::read_zkey`), and passing it to a prove function, then using proving_key.vk (from the zkey import also) in a verifier function, the proof will **not verify** correctly.

It does however verify correctly when using `generate_random_parameters`.
^ but it won't verify with snarkjs afterwards (with the pre-generated verifying key)

## Version

0.5.0-alpha
(https://github.com/arkworks-rs/groth16/tree/release-0.5.0)

## Steps to Reproduce

0. `let zkey_cursor = Cursor::new(std::fs::read(circuit.zkey))`
1. `let (proving_key, constraint_matrices) = ark_circom::read_zkey(&mut zkey_cursor)` should constraint_matrices be used for something?
2. `let cfg = CircomConfig::<ark_bn254::Fr>::new("circuit.wasm","circuit.r1cs")`
3. `let mut builder = CircomBuilder::new(cfg)`
4. `for (k, v) in inputs { builder.push_input(&k, v) }` inputs are `Vec<(String, Vec<BigInt>)>` 
5. `let circom = builder.build()`
6. `let pub_inputs = circom.get_public_inputs()` input amount matches the amount specified in verifying key
7. `let proof = Groth16::<Bn254>::prove(&proving_key, circom, &mut rng)` rng is `rand::thread_rng`
8. `let verified = Groth16::<Bn254>::verify(&proving_key.vk, &pub_inputs, &proof)` **== false!**

**Comment by mmagician** [comment]
I think these notes might help you: https://github.com/arkworks-rs/circom-compat/tree/release-0.5?tab=readme-ov-file#notes

**Comment by vaqxai** [comment]
Thanks, using `CircomReduction` helped, but it increased proving time. Ah well.
